apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: payments-load-balancer
spec:
  host: payments.prod.svc.cluster.local
  trafficPolicy:
      loadBalancer:
        simple: LEAST_CONN